import { describe, expect, it } from "vitest";
import type StampConfig from "../types/StampConfig.js";
import generateStamp from "./generateStamp.js";

const stamp: StampConfig = { generator: "test-gen", version: "1.0.0" };

describe("generateStamp", () => {
  it("generates single-line stamp for .ts files", () => {
    expect(generateStamp("file.ts", stamp)).toBe(
      "// Generated by test-gen v1.0.0",
    );
  });

  it("generates block stamp for .css files (preferBlock)", () => {
    expect(generateStamp("style.css", stamp)).toBe(
      "/* Generated by test-gen v1.0.0 */",
    );
  });

  it("generates block stamp for .html files (block only, no single)", () => {
    expect(generateStamp("page.html", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->",
    );
  });

  it("generates JSX stamp for .mdx files", () => {
    expect(generateStamp("doc.mdx", stamp)).toBe(
      "{/* Generated by test-gen v1.0.0 */}",
    );
  });

  it("generates hash stamp for .py files", () => {
    expect(generateStamp("main.py", stamp)).toBe(
      "# Generated by test-gen v1.0.0",
    );
  });

  it("returns null for .json (no single or block comment)", () => {
    expect(generateStamp("data.json", stamp)).toBeNull();
  });

  it("returns null for unknown extensions", () => {
    expect(generateStamp("file.dat", stamp)).toBeNull();
  });
});
