import type StampConfig from "../types/StampConfig.js";
import getCommentStyle from "./getCommentStyle.js";

/**
 * Generate a stamp comment for a generated file.
 * Returns null if the file type doesn't support comments.
 */
export default function generateStamp(
  filePath: string,
  options: StampConfig,
): string | null {
  const style = getCommentStyle(filePath);
  if (!style) return null;
  if (!style.single && !style.blockStart) return null;

  const stampText = `Generated by ${options.generator} v${options.version}`;

  if (style.preferBlock || (!style.single && style.blockStart)) {
    return `${style.blockStart} ${stampText} ${style.blockEnd}`;
  }

  /* v8 ignore next -- unreachable false branch: if we reach here, style.single is always truthy */
  if (style.single) {
    return `${style.single} ${stampText}`;
  }

  /* v8 ignore next -- structurally unreachable: line 14 guards !style.single && !style.blockStart */
  throw new Error(`No comment syntax for stamp in ${filePath}`);
}
