type CommentFormat = "line" | "html" | "jsx";

interface GeneratorCommentOptions {
  version?: string;
  timestamp?: boolean;
  /** Comment format. Defaults to "line" (`// ...`). */
  format?: CommentFormat;
}

const DELIMITERS: Record<CommentFormat, { start: string; end: string }> = {
  line: { start: "// ", end: "" },
  html: { start: "<!-- ", end: " -->" },
  jsx: { start: "{/* ", end: " */}" },
};

/**
 * Generate a metadata comment for generated files.
 *
 * @param format - "line" for `// ...`, "html" for `<!-- ... -->`, "jsx" for `{/* ... * /}`
 */
export default function generatorComment(
  generatorName: string,
  options?: GeneratorCommentOptions,
): string {
  const parts = [`Generated by ${generatorName}`];
  if (options?.version) parts.push(`v${options.version}`);
  if (options?.timestamp) parts.push(`on ${new Date().toISOString()}`);

  const format = options?.format ?? "line";
  const { start, end } = DELIMITERS[format];
  return `${start}${parts.join(" ")}${end}`;
}
