/**
 * GENERATED by `bun run generate:registry` from definitions/style-keys.yaml.
 * Do not edit: change the roster and regenerate. The Turtle form of the same
 * facts is definitions/registry.ttl, which also carries the roster's
 * provenance, and CI diffs both.
 */

export type ValueKind = "token" | "primitive" | "either";

export interface StyleKeyEntry {
  /** What the key admits: a symbol, a primitive, or either. */
  readonly valueKind: ValueKind;
  /**
   * Dotted prefixes whose symbols the key admits, channels included. A key
   * that admits several base namespaces carries the three spellings of each.
   */
  readonly tokenNamespace: readonly string[];
}

/** Segments that mark a value as a placeholder rather than a symbol (§4.1). */
export const PLACEHOLDER_SEGMENTS: readonly string[] = [
  "sth",
  "tbd",
  "xxx",
  "todo",
];

/** One entry per canonical style key. The roster is closed. */
export const STYLE_KEYS: Record<string, StyleKeyEntry> = {
  "appearance.background": {
    valueKind: "either",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.background.image": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.background.position": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.background.repeat": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.background.size": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.border.block.start.color": {
    valueKind: "token",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.border.bottom.color": {
    valueKind: "token",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.border.color": {
    valueKind: "either",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.border.inline.end.color": {
    valueKind: "token",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.border.style": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.border.top.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "appearance.border.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "appearance.native": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.opacity": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.outline.color": {
    valueKind: "either",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "appearance.outline.offset": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "appearance.outline.style": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "appearance.outline.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "appearance.radius": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "appearance.visibility": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "interaction.cursor": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "interaction.pointerEvents": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "interaction.resize": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "interaction.select": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.align": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.alignContent": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.alignSelf": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.boxSizing": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.container": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.direction": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.flex.basis": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.flex.grow": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.flex.shrink": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.area": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.autoFlow": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.autoRows": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.column": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.columns": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.row": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.grid.rows": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.justify": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.listStyle": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.objectFit": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.offset.block.end": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.block.start": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.bottom": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.inline.start": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.left": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.right": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.offset.top": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "layout.order": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.overflow": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.overflow.block": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.overflow.inline": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.overscroll": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.position": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.stack": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.table.collapse": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.table.layout": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.table.spacing": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.type": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.verticalAlign": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "layout.wrap": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "motion.duration": {
    valueKind: "either",
    tokenNamespace: ["motion.", "modifier.motion.", "surface.motion."],
  },
  "motion.easing": {
    valueKind: "either",
    tokenNamespace: ["motion.", "modifier.motion.", "surface.motion."],
  },
  "motion.property": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "size.block": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.height": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.inline": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.max.block": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.max.height": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.max.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.min.block": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.min.height": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.min.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "size.width": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.block.end": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.block.start": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.bottom": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.inline.end": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.inline.start": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.left": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.right": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.external.top": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.gap": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.gap.block": {
    valueKind: "token",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.gap.inline": {
    valueKind: "token",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.block.end": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.block.start": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.bottom": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.inline.end": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.inline.start": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.left": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "spacing.internal.top": {
    valueKind: "either",
    tokenNamespace: ["spacing.", "modifier.spacing.", "surface.spacing.", "dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "typography.align": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.color": {
    valueKind: "either",
    tokenNamespace: ["color.", "modifier.color.", "surface.color."],
  },
  "typography.decoration": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.decoration.offset": {
    valueKind: "token",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "typography.decoration.thickness": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "typography.direction": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.font": {
    valueKind: "either",
    tokenNamespace: ["typography.", "modifier.typography.", "surface.typography."],
  },
  "typography.fontFamily": {
    valueKind: "either",
    tokenNamespace: ["typography.", "modifier.typography.", "surface.typography."],
  },
  "typography.letterSpacing": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "typography.lineHeight": {
    valueKind: "either",
    tokenNamespace: ["typography.", "modifier.typography.", "surface.typography."],
  },
  "typography.overflow": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.size": {
    valueKind: "either",
    tokenNamespace: ["dimension.", "modifier.dimension.", "surface.dimension."],
  },
  "typography.variant.caps": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.variant.numeric": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.weight": {
    valueKind: "either",
    tokenNamespace: ["typography.", "modifier.typography.", "surface.typography."],
  },
  "typography.whiteSpace": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
  "typography.wrap": {
    valueKind: "primitive",
    tokenNamespace: [],
  },
};

/** Whether the key admits a token symbol at all. */
export function takesToken(key: string): boolean {
  const entry = STYLE_KEYS[key];
  return entry !== undefined && entry.valueKind !== "primitive";
}
