import getCommentStyle from "../template/getCommentStyle.js";
import type StampConfig from "../types/StampConfig.js";

/**
 * The prologue a stamp must stay BELOW: a shebang, a PHP open tag, or an XML
 * declaration must remain the file's first bytes or the file stops working
 * (interpreter selection, PHP emitting the comment as page text, ill-formed
 * XML). Returns the offset just past the prologue (including its newline when
 * present), or null when the content has no prologue.
 */
function prologueEnd(content: string): number | null {
  if (content.startsWith("#!")) {
    const newline = content.indexOf("\n");
    return newline === -1 ? content.length : newline + 1;
  }
  if (content.startsWith("<?php")) {
    // Protect the opening TOKEN, not the whole first line: a one-line
    // template (`<?php echo 'hi'; ?>`) must get the stamp right after the
    // tag — advancing to the newline would land it after `?>`, as page text.
    const afterTag = "<?php".length;
    return content.charAt(afterTag) === "\n" ? afterTag + 1 : afterTag;
  }
  if (content.startsWith("<?xml")) {
    const close = content.indexOf("?>");
    if (close !== -1) {
      const after = close + 2;
      return content.charAt(after) === "\n" ? after + 1 : after;
    }
  }
  return null;
}

/**
 * Apply a stamp to file content based on file extension. Uses the same
 * comment-style table as {@link getCommentStyle} — one source, no drift.
 * Returns the original content when the file type doesn't support comments,
 * and is IDEMPOTENT: content already carrying this exact stamp line is
 * returned unchanged, so driving the same WriteFile effect twice (preview
 * then run, or a re-drive) cannot stack stamps.
 */
export default function applyStamp(
  filePath: string,
  content: string,
  stamp: StampConfig,
): string {
  const style = getCommentStyle(filePath);

  if (!style) {
    return content;
  }

  const stampText = `Generated by ${stamp.generator} v${stamp.version}`;
  let stampLine: string;

  if (style.single && !style.preferBlock) {
    stampLine = `${style.single} ${stampText}`;
  } else if (style.blockStart && style.blockEnd) {
    stampLine = `${style.blockStart} ${stampText} ${style.blockEnd}`;
  } else {
    return content;
  }

  if (content.includes(stampLine)) {
    return content;
  }

  // A short-echo opener (`<?=`) takes an expression, not statements — there
  // is no safe line to claim, so leave the file unstamped.
  if (content.startsWith("<?=")) {
    return content;
  }

  const at = prologueEnd(content);
  if (at !== null) {
    const head = content.slice(0, at);
    const rest = content.slice(at);
    const separator = head.endsWith("\n") ? "" : "\n";
    return `${head}${separator}${stampLine}\n\n${rest}`;
  }

  return `${stampLine}\n\n${content}`;
}
