import { type Effect, mkdir, pure, task, writeFile } from "@canonical/task";
import { describe, expect, it, vi } from "vitest";
import type StampConfig from "../types/StampConfig.js";
import applyStamp from "./applyStamp.js";
import runTaskWithStamp from "./runTaskWithStamp.js";

const stamp: StampConfig = { generator: "test-gen", version: "1.0.0" };

// =============================================================================
// applyStamp
// =============================================================================

describe("applyStamp", () => {
  it("stamps TypeScript files with single-line comment", () => {
    expect(applyStamp("file.ts", "const x = 1;", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nconst x = 1;",
    );
  });

  it("stamps TSX files with single-line comment", () => {
    expect(applyStamp("Component.tsx", "<div />", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n<div />",
    );
  });

  it("stamps JavaScript files with single-line comment", () => {
    expect(applyStamp("app.js", "console.log(1);", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nconsole.log(1);",
    );
  });

  it("stamps CSS files with block comment (preferBlock)", () => {
    expect(applyStamp("styles.css", "body {}", stamp)).toBe(
      "/* Generated by test-gen v1.0.0 */\n\nbody {}",
    );
  });

  it("stamps SCSS files with single-line comment", () => {
    expect(applyStamp("styles.scss", "$color: red;", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n$color: red;",
    );
  });

  it("stamps HTML files with HTML comment", () => {
    expect(applyStamp("page.html", "<div></div>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<div></div>",
    );
  });

  it("stamps SVG files with HTML comment", () => {
    expect(applyStamp("icon.svg", "<svg></svg>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<svg></svg>",
    );
  });

  it("stamps Svelte files with HTML comment", () => {
    expect(applyStamp("App.svelte", "<script></script>", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<script></script>",
    );
  });

  it("stamps MDX files with JSX comment", () => {
    expect(applyStamp("doc.mdx", "# Hello", stamp)).toBe(
      "{/* Generated by test-gen v1.0.0 */}\n\n# Hello",
    );
  });

  it("stamps SQL files with double-dash comment", () => {
    expect(applyStamp("query.sql", "SELECT 1;", stamp)).toBe(
      "-- Generated by test-gen v1.0.0\n\nSELECT 1;",
    );
  });

  it("stamps YAML files with hash comment", () => {
    expect(applyStamp("config.yaml", "key: value", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nkey: value",
    );
  });

  it("stamps YML files with hash comment", () => {
    expect(applyStamp("ci.yml", "name: CI", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nname: CI",
    );
  });

  it("stamps shell scripts with hash comment", () => {
    expect(applyStamp("setup.sh", "echo hi", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\necho hi",
    );
  });

  it("stamps Python files with hash comment", () => {
    expect(applyStamp("main.py", "print(1)", stamp)).toBe(
      "# Generated by test-gen v1.0.0\n\nprint(1)",
    );
  });

  it("stamps Go files with single-line comment", () => {
    expect(applyStamp("main.go", "package main", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\npackage main",
    );
  });

  it("stamps Rust files with single-line comment", () => {
    expect(applyStamp("lib.rs", "fn main() {}", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\nfn main() {}",
    );
  });

  it("stamps Markdown files with HTML comment", () => {
    expect(applyStamp("README.md", "# Title", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n# Title",
    );
  });

  it("returns content unchanged for JSON (no comment syntax)", () => {
    const content = '{ "key": "value" }';
    expect(applyStamp("package.json", content, stamp)).toBe(content);
  });

  it("returns content unchanged for unknown extension", () => {
    const content = "binary data";
    expect(applyStamp("file.dat", content, stamp)).toBe(content);
  });

  it("returns content unchanged for extensionless files", () => {
    const content = "some content";
    expect(applyStamp("Makefile", content, stamp)).toBe(content);
  });

  it("handles shebang — places stamp after shebang line", () => {
    const content = "#!/bin/bash\necho hello";
    expect(applyStamp("script.sh", content, stamp)).toBe(
      "#!/bin/bash\n# Generated by test-gen v1.0.0\n\necho hello",
    );
  });

  it("handles shebang in .ts files", () => {
    const content = "#!/usr/bin/env bun\nconsole.log('hi');";
    expect(applyStamp("cli.ts", content, stamp)).toBe(
      "#!/usr/bin/env bun\n// Generated by test-gen v1.0.0\n\nconsole.log('hi');",
    );
  });

  it("keeps a newline-less shebang on the first line", () => {
    // The shebang must stay the file's first bytes — a stamp above it breaks
    // interpreter selection.
    const content = "#!/bin/bash";
    expect(applyStamp("script.sh", content, stamp)).toBe(
      "#!/bin/bash\n# Generated by test-gen v1.0.0\n\n",
    );
  });

  it("places the stamp after a PHP open tag, never above it", () => {
    const content = "<?php\necho 'hi';\n";
    expect(applyStamp("page.php", content, stamp)).toBe(
      "<?php\n// Generated by test-gen v1.0.0\n\necho 'hi';\n",
    );
  });

  it("stamps a one-line PHP template inside the PHP tag", () => {
    // The prologue is the opening TOKEN: advancing to the first newline
    // would append the stamp after `?>`, where it renders as page text.
    const content = "<?php echo 'hi'; ?>\n";
    expect(applyStamp("page.php", content, stamp)).toBe(
      "<?php\n// Generated by test-gen v1.0.0\n\n echo 'hi'; ?>\n",
    );
  });

  it("leaves a short-echo (<?=) PHP template unstamped", () => {
    // `<?=` takes an expression, not statements — there is no safe line.
    const content = "<?= $greeting ?>\n";
    expect(applyStamp("page.php", content, stamp)).toBe(content);
  });

  it("places the stamp after an XML declaration, never above it", () => {
    // The XML declaration must be the document's first bytes.
    const content = '<?xml version="1.0"?>\n<svg></svg>\n';
    expect(applyStamp("icon.svg", content, stamp)).toBe(
      '<?xml version="1.0"?>\n<!-- Generated by test-gen v1.0.0 -->\n\n<svg></svg>\n',
    );
  });

  it("handles an XML declaration with no newline after it", () => {
    const content = '<?xml version="1.0"?><svg></svg>';
    expect(applyStamp("icon.svg", content, stamp)).toBe(
      '<?xml version="1.0"?>\n<!-- Generated by test-gen v1.0.0 -->\n\n<svg></svg>',
    );
  });

  it("falls back to a plain prepend for an unterminated XML declaration", () => {
    // Malformed input ('<?xml' with no '?>'): no prologue to protect.
    const content = '<?xml version="1.0"';
    expect(applyStamp("icon.svg", content, stamp)).toBe(
      `<!-- Generated by test-gen v1.0.0 -->\n\n${content}`,
    );
  });

  it("stamps an svg without an XML declaration at the top", () => {
    expect(applyStamp("icon.svg", "<svg></svg>\n", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n<svg></svg>\n",
    );
  });

  it("is idempotent — re-stamping already-stamped content is a no-op", () => {
    // The runner mutates shared WriteFile effect objects in place; a second
    // drive of the same effect must not stack a second stamp.
    const once = applyStamp("file.ts", "content\n", stamp);
    expect(applyStamp("file.ts", once, stamp)).toBe(once);
  });

  it("covers the extensions the shared comment-style table knows", () => {
    // applyStamp previously kept a private, drifted copy of the table that
    // lacked these entries entirely.
    expect(applyStamp("script.fish", "echo hi\n", stamp)).toContain(
      "# Generated by",
    );
    expect(applyStamp("tool.pl", "print 1;\n", stamp)).toContain(
      "# Generated by",
    );
    expect(applyStamp("lib.hpp", "int x;\n", stamp)).toContain(
      "// Generated by",
    );
  });

  it("handles empty content", () => {
    expect(applyStamp("file.ts", "", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\n",
    );
  });

  it("handles compound extension (.test.ts) — uses final extension", () => {
    expect(applyStamp("app.test.ts", "test()", stamp)).toBe(
      "// Generated by test-gen v1.0.0\n\ntest()",
    );
  });

  it("handles uppercase extensions via lowercase normalization", () => {
    expect(applyStamp("README.MD", "# Title", stamp)).toBe(
      "<!-- Generated by test-gen v1.0.0 -->\n\n# Title",
    );
  });

  it("includes generator name and version in stamp text", () => {
    const customStamp: StampConfig = {
      generator: "@canonical/summon-component",
      version: "0.3.2",
    };
    expect(applyStamp("file.ts", "code", customStamp)).toBe(
      "// Generated by @canonical/summon-component v0.3.2\n\ncode",
    );
  });
});

// =============================================================================
// runTaskWithStamp
// =============================================================================

describe("runTaskWithStamp", () => {
  it("runs a pure task without stamp option", async () => {
    const result = await runTaskWithStamp(pure(42));
    expect(result).toBe(42);
  });

  it("runs a pure task with stamp option (no WriteFile effects to stamp)", async () => {
    const result = await runTaskWithStamp(pure("done"), {
      stamp,
    });
    expect(result).toBe("done");
  });

  it("stamps WriteFile effect content when stamp is provided", async () => {
    const captured: Effect[] = [];
    const task = writeFile("/tmp/test-stamp-output.ts", "const x = 1;");

    await runTaskWithStamp(task, {
      stamp,
      onEffectStart: (effect) => {
        captured.push({ ...effect });
      },
    });

    const writeEffect = captured.find((e) => e._tag === "WriteFile");
    expect(writeEffect).toBeDefined();
    // The content should have been mutated before our onEffectStart was called
    expect((writeEffect as { content: string }).content).toContain(
      "Generated by test-gen v1.0.0",
    );
  });

  it("calls user-provided onEffectStart after stamping", async () => {
    const userCallback = vi.fn();
    const task = writeFile("/tmp/test-stamp-cb.ts", "hello");

    await runTaskWithStamp(task, {
      stamp,
      onEffectStart: userCallback,
    });

    expect(userCallback).toHaveBeenCalled();
    const callArg = userCallback.mock.calls[0][0];
    expect(callArg._tag).toBe("WriteFile");
  });

  it("does not modify non-WriteFile effects", async () => {
    const captured: Effect[] = [];
    // mkdir produces a MakeDir effect, not WriteFile
    const mkdirTask = task(mkdir("/tmp/test-stamp-dir"))
      .chain(() => task(writeFile("/tmp/test-stamp-dir/out.ts", "code")))
      .unwrap();

    await runTaskWithStamp(mkdirTask, {
      stamp,
      onEffectStart: (effect) => {
        captured.push({ ...effect });
      },
    });

    const mkdirEffect = captured.find((e) => e._tag === "MakeDir");
    expect(mkdirEffect).toBeDefined();
    // MakeDir effect should pass through unchanged
    expect(mkdirEffect?._tag).toBe("MakeDir");
  });
});
