/**
 * `anatomies/register.yaml` — the committed record of every exception (ADR J §5.3).
 *
 * The register is the law's exception clause: an element that resolves in neither S1
 * nor S2 passes only because a row admits it. That makes the file's integrity the
 * point, and two rules follow from it.
 *
 * **`validate --write-register` is the only writer**, and it regenerates every
 * mechanical field of every row — identity, `category`, `considered`, `date` —
 * **preserving the hand-written `rationale`** of a row with the same identity,
 * `category` included in that identity. Without the category in the identity the two
 * rows an X7-plus-X8 element carries would share one, and neither the preservation nor
 * the drift diff would be single-valued.
 *
 * **The register is not committed yet.** 130 of the 160 rows a run produces today are
 * one category — the parse failures of the retired notation — and every one of them
 * disappears as the anatomies are authored by hand, so the file would land at eight times its
 * steady-state size and be rewritten wholesale on the next rung. `validate` writes it
 * on every run and reads it back through `readRegister`, which treats a missing file
 * as an empty register; `anatomies/census.json` carries the per-category counts and
 * the `unresolved` list, and its diff is what CI gates on. When the migration lands,
 * the file is committed and `git diff --exit-code anatomies/register.yaml` becomes the
 * gate that keeps a renamed symbol or a lazy classification from moving silently.
 *
 * `RegisterRow` itself is defined in `src/transform/tokenBindings.ts`, beside the law
 * that reads it — the import here is type-only and erases, so the two modules do not
 * form a runtime cycle.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { Document, parseDocument, YAMLMap, YAMLSeq } from "yaml";
import type { RegisterRow } from "../transform/tokenBindings.js";

/** Where the register lives, relative to the repository root. */
export const REGISTER_PATH = "anatomies/register.yaml";

/** The register's own header, rewritten on every regeneration. */
const HEADER = `
anatomies/register.yaml — every exception the law admits

GENERATED by \`bun src/cli.ts anatomies validate --write-register\`, which is its
only writer. Every mechanical field is regenerated from the corpus and the token
strata; the hand-written \`rationale\` of a row is preserved across a regeneration,
keyed on the row's identity (uri, node, key, state, value, category).

Do not add or remove a row by hand: a row nothing in the corpus needs fails
validation, and an element with no row fails it too. Write the rationale, and let
the run place the row.

Each category carries a count below, or a count of 0 with a one-line reason, so a
category that empties is visible rather than absent.
`.trim();

/** A category's count, and — when it is zero — why. */
export interface CategoryCount {
  count: number;
  /** Required when `count` is 0, so an empty category is explained and not just absent. */
  reason?: string;
}

/** The whole register: the per-category counts and the rows. */
export interface Register {
  categories: Record<string, CategoryCount>;
  rows: RegisterRow[];
}

/**
 * A row's identity, `category` included.
 *
 * It is what the preservation and the drift diff are keyed on, and it is deliberately
 * not the binding's six-tuple: a register row may leave `uri`, `node`, `key` and
 * `state` null (a row no key binds, or a token-side row), and `value` — the element as
 * written — is what makes it specific.
 */
export function rowIdentity(row: RegisterRow): string {
  return [
    row.uri ?? "-",
    row.node ?? "-",
    row.key ?? "-",
    row.state ?? "-",
    row.value,
    row.category,
  ].join(" | ");
}

/** Rows in the file's canonical order: category, then identity. */
export function sortRows(rows: readonly RegisterRow[]): RegisterRow[] {
  return [...rows].sort((left, right) => {
    const byCategory =
      categoryOrder(left.category) - categoryOrder(right.category);
    return byCategory !== 0
      ? byCategory
      : rowIdentity(left).localeCompare(rowIdentity(right));
  });
}

/** `X15` sorts after `X2`, which a string comparison would get wrong. */
function categoryOrder(category: string): number {
  const digits = category.replace(/^X/, "");
  const value = Number(digits);
  return Number.isNaN(value) ? Number.MAX_SAFE_INTEGER : value;
}

function scalar(value: unknown): string | number | null {
  if (value === null || value === undefined) {
    return null;
  }
  return value as string | number;
}

/**
 * Parse a register document.
 *
 * A malformed register is a hard error, never an empty one. Reading it as empty would
 * turn the law's exception clause off silently: every admitted element would become an
 * unresolved-symbol finding, and the reader would look for the defect in the corpus
 * rather than in the file that failed to parse.
 *
 * @throws when the YAML is malformed, or a row is missing a required field.
 */
export function parseRegister(text: string): Register {
  const document = parseDocument(text);
  if (document.errors.length > 0) {
    throw new Error(
      `${REGISTER_PATH} does not parse: ${document.errors[0].message}`,
    );
  }
  const parsed = document.toJS() as {
    categories?: Record<string, CategoryCount>;
    rows?: RegisterRow[];
  } | null;
  for (const [index, entry] of (parsed?.rows ?? []).entries()) {
    for (const field of ["value", "category", "date"] as const) {
      if (entry?.[field] === undefined || entry[field] === null) {
        throw new Error(
          `${REGISTER_PATH} row ${index + 1} is missing \`${field}\``,
        );
      }
    }
  }
  return {
    categories: parsed?.categories ?? {},
    rows: (parsed?.rows ?? []).map((row) => ({
      uri: scalar(row.uri) as string | null,
      node: scalar(row.node) as string | null,
      key: scalar(row.key) as string | null,
      state: scalar(row.state) as string | null,
      value: String(row.value),
      category: String(row.category),
      considered: row.considered ?? [],
      ...(row.rationale === undefined ? {} : { rationale: row.rationale }),
      date: String(row.date),
    })),
  };
}

/**
 * Read the register from disk.
 *
 * A **missing** file is an empty register: before J-4 there are no exceptions to
 * carry, and the guard has to run anyway. Any other failure — an unreadable path, a
 * malformed document — propagates, because a register that silently reads as empty
 * would turn the law's exception clause off without telling anyone.
 */
export function readRegister(path: string = REGISTER_PATH): Register {
  let text: string;
  try {
    text = readFileSync(path, "utf-8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return { categories: {}, rows: [] };
    }
    throw error;
  }
  return parseRegister(text);
}

/**
 * Merge freshly derived rows with the register on disk.
 *
 * The derived set is authoritative for which rows exist and for every mechanical
 * field. Two things are carried across, and only onto a row whose identity matches
 * exactly:
 *
 * - **`rationale`**, because it is hand-written and the regeneration must not eat it;
 * - **`date`**, because it records when the exception was first registered, not when
 *   the generator last ran. Taking the run's date would rewrite every row on every
 *   run, and `git diff --exit-code anatomies/register.yaml` — the gate — would then be
 *   red every day for no reason and green for nothing.
 */
export function mergeRationale(
  derived: readonly RegisterRow[],
  existing: readonly RegisterRow[],
): RegisterRow[] {
  const known = new Map<string, RegisterRow>();
  for (const row of existing) {
    known.set(rowIdentity(row), row);
  }
  return derived.map((row) => {
    const previous = known.get(rowIdentity(row));
    if (previous === undefined) {
      return row;
    }
    const rationale = row.rationale ?? previous.rationale;
    return {
      ...row,
      ...(rationale === undefined || rationale === "" ? {} : { rationale }),
      date: previous.date,
    };
  });
}

/** Render a register as YAML, deterministically, with its header comment. */
export function renderRegister(register: Register): string {
  const document = new Document({});
  document.commentBefore = HEADER.split("\n")
    .map((line) => (line === "" ? "" : ` ${line}`))
    .join("\n");

  const categories = new YAMLMap();
  for (const key of Object.keys(register.categories).sort(
    (left, right) => categoryOrder(left) - categoryOrder(right),
  )) {
    const entry = register.categories[key];
    const value = new YAMLMap();
    value.flow = true;
    value.set("count", entry.count);
    if (entry.count === 0) {
      value.set("reason", entry.reason ?? "no instance in the corpus");
    }
    categories.set(key, value);
  }

  const rows = new YAMLSeq();
  for (const row of sortRows(register.rows)) {
    const entry = new YAMLMap();
    entry.set("uri", row.uri);
    entry.set("node", row.node);
    entry.set("key", row.key);
    entry.set("state", row.state);
    entry.set("value", row.value);
    entry.set("category", row.category);
    const considered = new YAMLSeq();
    considered.flow = true;
    for (const symbol of row.considered) {
      considered.add(symbol);
    }
    entry.set("considered", considered);
    if (row.rationale !== undefined) {
      entry.set("rationale", row.rationale);
    }
    entry.set("date", row.date);
    rows.add(entry);
  }

  const root = new YAMLMap();
  root.set("categories", categories);
  root.set("rows", rows);
  document.contents = root;
  return document.toString({ lineWidth: 0 });
}

/** Write the register to disk. The single writer's single write. */
export function writeRegister(
  register: Register,
  path: string = REGISTER_PATH,
): void {
  writeFileSync(path, renderRegister(register), "utf-8");
}
