import { collectUndos } from "@canonical/task";
import { describe, expect, it } from "vitest";
import dryRunWithFileState from "./dryRunWithFileState.js";
import removeLineFromFile from "./removeLineFromFile.js";

describe("removeLineFromFile", () => {
  it("removes a matching line from multi-line content", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "line2"),
      { "/src/index.ts": "line1\nline2\nline3" },
    );

    const writeEffect = result.effects.find((e) => e._tag === "WriteFile");
    expect(writeEffect).toBeDefined();
    expect((writeEffect as { content: string }).content).toBe("line1\nline3");
  });

  it("is a true no-op when the line is not present (no rewrite)", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "nonexistent"),
      { "/src/index.ts": "line1\nline3" },
    );

    const writes = result.effects.filter(
      (e) => e._tag === "WriteFile" || e._tag === "DeleteFile",
    );
    expect(writes).toHaveLength(0);
  });

  it("never deletes a file that was already empty", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "anything"),
      { "/src/index.ts": "" },
    );

    const writes = result.effects.filter(
      (e) => e._tag === "WriteFile" || e._tag === "DeleteFile",
    );
    expect(writes).toHaveLength(0);
  });

  it("deletes file when content becomes empty after removal", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "only-line"),
      { "/src/index.ts": "only-line\n" },
    );

    const deleteEffect = result.effects.find((e) => e._tag === "DeleteFile");
    expect(deleteEffect).toBeDefined();
    expect((deleteEffect as { path: string }).path).toBe("/src/index.ts");
  });

  it("deletes file when only a generator stamp remains after removal", () => {
    const stamp = "// Generated by @canonical/summon-component:react v0.1.0";
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", 'export * from "./Button/index.js";'),
      {
        "/src/index.ts": `${stamp}\nexport * from "./Button/index.js";\n`,
      },
    );

    const deleteEffect = result.effects.find((e) => e._tag === "DeleteFile");
    expect(deleteEffect).toBeDefined();
  });

  it("keeps the file when non-stamp content remains after removal", () => {
    const stamp = "// Generated by @canonical/summon-component:react v0.1.0";
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", 'export * from "./Button/index.js";'),
      {
        "/src/index.ts": `${stamp}\nexport * from "./Button/index.js";\nexport * from "./Card/index.js";\n`,
      },
    );

    const writeEffect = result.effects.find((e) => e._tag === "WriteFile");
    expect(writeEffect).toBeDefined();
    expect((writeEffect as { content: string }).content).toBe(
      `${stamp}\nexport * from "./Card/index.js";\n`,
    );
    expect(result.effects.some((e) => e._tag === "DeleteFile")).toBe(false);
  });

  it("trims whitespace when matching lines", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "  target  "),
      { "/src/index.ts": "before\n  target  \nafter" },
    );

    const writeEffect = result.effects.find((e) => e._tag === "WriteFile");
    expect(writeEffect).toBeDefined();
    expect((writeEffect as { content: string }).content).toBe("before\nafter");
  });

  it("removes all matching lines", () => {
    const result = dryRunWithFileState(
      removeLineFromFile("/src/index.ts", "dup"),
      { "/src/index.ts": "dup\nkeep\ndup" },
    );

    const writeEffect = result.effects.find((e) => e._tag === "WriteFile");
    expect(writeEffect).toBeDefined();
    expect((writeEffect as { content: string }).content).toBe("keep");
  });

  it("uses { undo: null } on internal effects to prevent undo chains", () => {
    const undos = collectUndos(removeLineFromFile("/src/index.ts", "line"));
    expect(undos).toHaveLength(0);
  });
});
