import {
  deleteFile,
  flatMap,
  pure,
  readFile,
  type Task,
  writeFile,
} from "@canonical/task";

/**
 * Whether every non-blank line is a generator-stamp comment (the header the
 * runner prepends to generated files: `<comment> Generated by <name> v<ver>`).
 * Such a remainder carries no exports of its own, so the file counts as empty
 * when deciding whether to delete it. Vacuously true for a blank remainder.
 */
const isEffectivelyEmpty = (content: string): boolean =>
  content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "")
    .every((line) => /^(?:\/\/|\/\*+|\*|#|<!--)\s*Generated by /.test(line));

/**
 * Remove a specific line from a file (all occurrences, matched by trimmed
 * content). Truly idempotent: when the line is not present the file is left
 * untouched — no rewrite, and a file that was already empty is never deleted.
 * When the removal leaves the file effectively empty (blank, or only
 * generator-stamp comment lines), the file is deleted entirely.
 */
export default function removeLineFromFile(
  filePath: string,
  line: string,
): Task<void> {
  return flatMap(readFile(filePath), (content) => {
    const trimmedLine = line.trim();
    const lines = content.split("\n");
    const kept = lines.filter((l) => l.trim() !== trimmedLine);

    if (kept.length === lines.length) {
      // Line not present: leave the file exactly as it was.
      return pure(undefined);
    }

    const filtered = kept.join("\n");
    if (isEffectivelyEmpty(filtered)) {
      return deleteFile(filePath, { undo: null });
    }
    return writeFile(filePath, filtered, { undo: null });
  });
}
