/**
 * PROTECTED — pragma's side of the byte-equality seam contract: every `create`
 * tree is produced TWO ways and diffed byte-for-byte (path set + contents, incl.
 * the "Generated by" stamp): (1) `pragma create <verb> --yes` through the kernel
 * dispatcher, and (2) the REFERENCE — summon-core `execute` with `autoPrompt`,
 * run through `runGeneratorTask` + the shared stamp. They match because both
 * derive the StampConfig from `createGeneratorStamp` (displayName + version) and
 * run the SAME `generator.generate` with the SAME answers.
 *
 * The reference producer, the tree snapshot/diff, and the answer sets are NOT
 * defined here any more: they are `@canonical/summon-core/testing`, the named
 * conformance suite both bins run (L-OPEN-10). This file supplies what only
 * pragma can — its kernel dispatch path, and the mapping from a fixture's
 * logical generator id to the bundled generator plus the CLI param names the
 * `create` verbs take. No new package edge: pragma already depends on
 * summon-core, and never on the summon bin.
 *
 * Five generators are covered across seven fixtures: component × {react, svelte, lit},
 * package, and
 * application. A cross-binary subprocess guard lives in byteEquality.subprocess.test.ts.
 */

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  CONFORMANCE_FIXTURES,
  diffTrees,
  formatTreeDiff,
  isIdentical,
  produceReference,
  snapshotTree,
  type TreeSnapshot,
} from "@canonical/summon-core/testing";
import { describe, expect, it } from "vitest";
import { executeVerb } from "../../kernel/project/cli/dispatch.js";
import { bootRuntime } from "../../kernel/runtime/boot.js";
import type { GlobalFlags } from "../../kernel/runtime/types.js";
import type { VerbSpec } from "../../kernel/spec/types.js";
import { blankCanonicalRanges } from "../../testing/helpers/blankCanonicalRanges.js";
import { createVerbs } from "./create.verb.js";
import type { CreateKind } from "./types.js";

const FLAGS: GlobalFlags = {
  llm: false,
  autoLlm: false,
  format: "plain",
  verbose: false,
};
const freshCwd = (): string => mkdtempSync(join(tmpdir(), "pragma-golden-"));

/** Producer (1): the full pragma kernel path — dispatcher runs the create verb. */
async function producePragma(
  kind: CreateKind,
  params: Record<string, unknown>,
): Promise<TreeSnapshot> {
  const dir = freshCwd();
  const prev = process.cwd();
  process.chdir(dir);
  try {
    const outcome = await executeVerb(
      createVerbs[kind] as VerbSpec,
      params,
      { dryRun: false, undo: false, yes: true },
      bootRuntime(FLAGS, dir),
    );
    expect(outcome.exitCode).toBe(0);
  } finally {
    process.chdir(prev);
  }
  return snapshotTree(dir);
}

/**
 * Producer (2): the shared conformance REFERENCE, over pragma's own generator.
 *
 * The fixture names its generator logically; `pickGenerator` is what turns that
 * into the bundled definition. The suite never imports a generator itself —
 * summon-core sits below both bins.
 */
async function produceSummon(
  kind: CreateKind,
  framework: string,
  answers: Readonly<Record<string, unknown>>,
): Promise<TreeSnapshot> {
  const { pickGenerator } = await import("./pickGenerator.js");
  // pickGenerator is keyed by FULL COMMAND PATH now; this surface still
  // thinks in kind+framework, so map first (exactly as runCreate does).
  const commandPath =
    kind === "component"
      ? `component/${framework}`
      : kind === "package"
        ? "package"
        : "application/react";
  return produceReference({
    generator: pickGenerator(commandPath),
    answers,
  });
}

/**
 * One golden case: the shared fixture, plus what only pragma knows — which
 * bundled generator the fixture's id names, and the CLI param names the create
 * verb takes for the same answers.
 */
interface Case {
  readonly fixture: string;
  readonly kind: CreateKind;
  readonly framework: string;
  readonly params: Record<string, unknown>;
}

const componentAnswers = {
  withStyles: true,
  withStories: true,
  withSsrTests: false,
};

const cases: Case[] = [
  {
    fixture: "component/react",
    kind: "component",
    framework: "react",
    params: {
      framework: "react",
      componentPath: "src/components/Button",
      ...componentAnswers,
    },
  },
  {
    fixture: "component/svelte",
    kind: "component",
    framework: "svelte",
    params: {
      framework: "svelte",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
  },
  {
    fixture: "component/lit",
    kind: "component",
    framework: "lit",
    params: {
      framework: "lit",
      componentPath: "src/lib/Button",
      ...componentAnswers,
    },
  },
  {
    fixture: "package",
    kind: "package",
    framework: "",
    params: {
      name: "@canonical/my-lib",
      type: "library",
      description: "A library.",
      withReact: false,
      withStorybook: false,
      withCli: false,
      withPrTemplate: false,
      runInstall: false,
    },
  },
  {
    fixture: "application",
    kind: "application",
    framework: "",
    // The prompt names ARE the param names now (the B8 alias seam is gone):
    // the pragma path takes the generator's own `forms`/`relay` (ssr/router
    // are always-on facts, no longer prompts).
    params: {
      appPath: "my-app",
      forms: true,
      relay: false,
      runInstall: false,
    },
  },
  {
    fixture: "application-spa",
    kind: "application",
    framework: "",
    params: {
      appPath: "my-app",
      forms: true,
      intl: false,
      relay: false,
      rendering: "spa",
      runInstall: false,
    },
  },
  {
    fixture: "application-spa-all",
    kind: "application",
    framework: "",
    params: {
      appPath: "my-app",
      forms: true,
      intl: true,
      relay: true,
      rendering: "spa",
      runInstall: false,
    },
  },
];

describe("byte-equality goldens — pragma create \u2261 the conformance reference (PROTECTED)", () => {
  it("covers every shared conformance fixture", () => {
    // The suite's fixture list is the contract; a fixture added there and not
    // wired here would silently go unchecked on pragma's side.
    expect(cases.map((entry) => entry.fixture)).toEqual(
      CONFORMANCE_FIXTURES.map((entry) => entry.name),
    );
  });

  for (const testCase of cases) {
    it(`${testCase.fixture}: the kernel path matches the reference byte for byte`, async () => {
      const shared = CONFORMANCE_FIXTURES.find(
        (entry) => entry.name === testCase.fixture,
      );
      if (!shared) throw new Error(`no fixture "${testCase.fixture}"`);
      let pragma = await producePragma(testCase.kind, testCase.params);
      let reference = await produceSummon(
        testCase.kind,
        testCase.framework,
        shared.answers,
      );
      // Two independent `npm view` resolutions feed the application tree
      // (one per producer); blank the @canonical/* ranges identically so an
      // asymmetric registry outcome cannot red this template-surface cell —
      // range truth lives in the offline subprocess cells.
      if (testCase.kind === "application") {
        pragma = blankCanonicalRanges(pragma);
        reference = blankCanonicalRanges(reference);
      }
      expect(pragma.size).toBeGreaterThan(0);
      const diff = diffTrees(pragma, reference);
      expect(
        isIdentical(diff),
        formatTreeDiff(diff, "pragma create", "the conformance reference"),
      ).toBe(true);
    });
  }
});
