// Generated by @canonical/summon-package v0.36.0

/**
 * @canonical/token-ontology
 *
 * Semantic model of the Canonical design tokens: authored dt: ontology (definitions) and generated strata data, with TypeScript build scripts.
 */

export {};
