/** Map CSS properties to their expected value types where that is unambiguous. */
import type { CssValueType } from "../../types/index.js";

export const COLOR_PROPERTIES: ReadonlySet<string> = new Set([
  "color",
  "background-color",
  "background",
  "border-color",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "border-block-start-color",
  "border-block-end-color",
  "border-inline-start-color",
  "border-inline-end-color",
  "outline-color",
  "text-decoration-color",
  "fill",
  "stroke",
  "caret-color",
  "accent-color",
  "column-rule-color",
  "flood-color",
  "lighting-color",
  "stop-color",
]);

export const LENGTH_PROPERTIES: ReadonlySet<string> = new Set([
  "width",
  "height",
  "min-width",
  "max-width",
  "min-height",
  "max-height",
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "margin-block",
  "margin-block-start",
  "margin-block-end",
  "margin-inline",
  "margin-inline-start",
  "margin-inline-end",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "padding-block",
  "padding-block-start",
  "padding-block-end",
  "padding-inline",
  "padding-inline-start",
  "padding-inline-end",
  "top",
  "right",
  "bottom",
  "left",
  "inset",
  "gap",
  "row-gap",
  "column-gap",
  "font-size",
  // `line-height` is intentionally omitted: it also accepts a unitless
  // <number> multiplier (e.g. `line-height: 1.5`), which is not a
  // <length-percentage>, so treating it as strictly length produces false
  // type-mismatch diagnostics.
  "letter-spacing",
  "word-spacing",
  "border-width",
  "border-radius",
  "outline-width",
  "outline-offset",
  "block-size",
  "inline-size",
  "min-block-size",
  "max-block-size",
  "min-inline-size",
  "max-inline-size",
  "flex-basis",
]);

export const SHORTHAND_PROPERTIES: ReadonlySet<string> = new Set([
  "background",
  "border",
  "border-top",
  "border-right",
  "border-bottom",
  "border-left",
  "border-block",
  "border-block-start",
  "border-block-end",
  "border-inline",
  "border-inline-start",
  "border-inline-end",
  "flex",
  "grid",
  "grid-template",
  "grid-area",
  "grid-row",
  "grid-column",
  "list-style",
  "font",
  "transition",
  "animation",
  "text-decoration",
  "outline",
  "overflow",
  "place-items",
  "place-content",
  "place-self",
]);

export function expectedTypeForProperty(property: string): CssValueType | null {
  if (SHORTHAND_PROPERTIES.has(property)) return null;
  if (COLOR_PROPERTIES.has(property)) return "<color>";
  if (LENGTH_PROPERTIES.has(property)) return "<length-percentage>";
  return null;
}
